# Overview of Pandas and Numpy
## Pandas
Pandas is used to process data, it is like excel sheet, with rows and columns.  Columns have their respective name and Rows has index number.

Pandas provide functionality to load data from multiple source.  Process data cleanup, removing empty cells, or rows.  Validate and get quick insight on dataset.

Pandas also helps in creating data models and perform analysis.

There are two key concept 1st Dataframe and 2nd Dataseries.  As descripbed earlier dataframes are made out of columns and rows.  And on the other hand dataseries is single dimention array having any type of data, similar to a column.

In [1]:
import pandas as pd

df = pd.DataFrame({
    'a':[1,2,3],
    'b':[4,5,6],
    'c':[7,8,9]
})

print(f"Pandas DataFrame df: \n {df}")

data_series = df['a']

print(f"Pandas data series: \n {data_series}")

Pandas DataFrame df: 
    a  b  c
0  1  4  7
1  2  5  8
2  3  6  9
Pandas data series: 
 0    1
1    2
2    3
Name: a, dtype: int64


Basic operation in pandas
df.info(): provides details about dataframe and type of data it holds
df.describe(): provide statastical overview of the data column having numerical values, like mean, median, max, min, percentile
df.head(): provides top 5 rows of the datasets along with column headings

In [13]:
import pandas as pd

df = pd.DataFrame({
    'a':[1,2,3],
    'b':[4,5,6],
    'c':[7,8,9]
})

#print(f"Pandas DataFrame df: \n {df}")

print(f"Pandas data series:")
df.info()
df.describe()
df.head()

Pandas data series:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   a       3 non-null      int64
 1   b       3 non-null      int64
 2   c       3 non-null      int64
dtypes: int64(3)
memory usage: 204.0 bytes


a  b  c
0  1  4  7
1  2  5  8
2  3  6  9

## Numpy
Numpy is foundational library for Python to perform mathemetical calculation.  Numpy is implemented in C, it makes it fast and provides efficient way to implement mathematical operations on large data series.

Numpy array can be single dimention a series of data or multidimention like metrix.  It can perform methematica operation on single or multidimentional array.

Some of the basic operation, creating metrix, mathemetical operation on metrix, indexing and slicing, reshaping arrays.

In [16]:
# create single and multi dimention numpy array
import numpy as np
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([[1,2,3],[4,5,6]])
print(f"Numpy array arr1: \n {arr1}")
print(f"Numpy array arr2: \n {arr2}")

Numpy array arr1: 
 [1 2 3 4 5]
Numpy array arr2: 
 [[1 2 3]
 [4 5 6]]


In [19]:
# generate matrix
import numpy as np

zeros = np.zeros((3,3))
ones = np.ones((2,2))

print(f"Numpy generated 3 x 3 matrix: {zeros}")
print(f"Numpy generated 2 x 2 matrix: \n {ones}")

Numpy generated 3 x 3 matrix: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Numpy generated 2 x 2 matrix: 
 [[1. 1.]
 [1. 1.]]


In [21]:
# numpy arithmetic operation on matrix
import numpy as np

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([5,6,7,8,9])

arr3 = arr1 + arr2

print(f"arr1: {arr1}")
print(f"arr2: {arr2}")
print(f"sum of arr1 and arr2: {arr3}")

print(f"sqare of arr3: {np.square(arr3)}")
print(f"mean of arr3: {np.mean(arr3)}")
print(f"median of arr3: {np.median(arr3)}")

arr1: [1 2 3 4 5]
arr2: [5 6 7 8 9]
sum of arr1 and arr2: [ 6  8 10 12 14]
sqare of arr3: [ 36  64 100 144 196]
mean of arr3: 10.0
median of arr3: 10.0


In [23]:
#indexing and slicing
import numpy as np

arr = np.array([1,2,3,4,5,6])
print(f"value of numpy array arr: {arr}")

print(f"value at index 2: {arr[2]}")

print(f"slice arr elements from 2 to 4: {arr[2:4]}")


value of numpy array arr: [1 2 3 4 5 6]
value at index 2: 3
slice arr elements from 2 to 4: [3 4]


In [27]:
#reshape numpy array
import numpy as np

arr = np.array([[1,2,3],[4,5,6]])
print(f"numpy array arr: \n {arr}")

reshaped_arr = arr.reshape((3,2))
print(f"reshaped arr: \n {reshaped_arr}")

numpy array arr: 
 [[1 2 3]
 [4 5 6]]
reshaped arr: 
 [[1 2]
 [3 4]
 [5 6]]
