# Typecasting
## Scalar type casting
1. int(): convert to an integer

In [4]:
x = int(3.14)
print(f"value of x = {x}  and type of x: {type(x)}")

value of x = 3  and type of x: <class 'int'>


2. float(): convert to float value

In [1]:
x = float(2)
print(f"Value of x: {x} and data type of x: {type(x)}")

Value of x: 2.0 and data type of x: <class 'float'>


3. complex(): convert to complex number

In [2]:
x = complex(2)
print(f"Value of x: {x} and data type of x: {type(x)}")

Value of x: (2+0j) and data type of x: <class 'complex'>


4 str(): conver to string

In [3]:
x = str(3.14)
print(f"Value of x: {x} and data type of x: {type(x)}")

Value of x: 3.14 and data type of x: <class 'str'>


## Container Type
1 list()

In [1]:
x = list((1,2,3,4))
print(f"Value of x: {x} and data type of x: {type(x)}")

Value of x: [1, 2, 3, 4] and data type of x: <class 'list'>


2 tuple()

In [2]:
x = tuple([1,2,3,4])
print(f"Value of x: {x} and data type of x: {type(x)}")

Value of x: (1, 2, 3, 4) and data type of x: <class 'tuple'>


3 set()

In [3]:
x = set([1,2,3,4])
print(f"Value of x: {x} and data type of x: {type(x)}")

Value of x: {1, 2, 3, 4} and data type of x: <class 'set'>


4 frozenset()

In [4]:
x = frozenset([1,2,3,4])
print(f"Value of x: {x} and data type of x: {type(x)}")

Value of x: frozenset({1, 2, 3, 4}) and data type of x: <class 'frozenset'>


5 dict()

In [6]:
x = dict([('a',1),('b',2)])
print(f"Value of x: {x} and data type of x: {type(x)}")

Value of x: {'a': 1, 'b': 2} and data type of x: <class 'dict'>


## Advance type casting
1. to_numpy()

In [7]:
import pandas as pd
import numpy as np

#create pandas dataframe
df = pd.DataFrame({
    'a':[1,2,3],
    'b':[4,5,6],
    'c':[7,8,9]
})
print(f"pandas df: \n{df}")

#cast to numpy array
arr = df.to_numpy()
print(f"Numpy array: \n{arr}")

pandas df: 
   a  b  c
0  1  4  7
1  2  5  8
2  3  6  9
Numpy array: 
[[1 4 7]
 [2 5 8]
 [3 6 9]]


2. pd.dataframe():

In [8]:
import pandas as pd
import numpy as np

#numpy array
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(f"Numpy arr: \n {arr}")

#creating columns
columns = ['a','b','c']

#casting to pandas dataframe
df= pd.DataFrame(arr,columns=columns)
print(f"pandas df: \n {df}")

Numpy arr: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
pandas df: 
    a  b  c
0  1  2  3
1  4  5  6
2  7  8  9
